function apply_prettier(Axes)
%% General Axis
if strcmp(Axes.YAxisLocation, 'right')
    yyaxis left
end
set(Axes,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times',...
    'TickDir', 'out',...
    'box', 'off');
%% Left YLabel
if ~isempty(Axes.YLabel.String)
    ylabel(Axes.YLabel.String,...
        'FontUnits','points',...
        'interpreter','latex',...
        'FontSize', 12,...
        'FontName','Times')
end
%% XLabel
if ~isempty(Axes.XLabel.String)
    xlabel(Axes.XLabel.String,...
        'FontUnits','points',...
        'FontWeight','normal',...
        'interpreter','latex',...
        'FontSize',12,...
        'FontName','Times')
end
%% Legend
if ~isempty(Axes.Legend)
    legend(Axes.Legend.String,...
        'FontUnits', 'points',...
        'interpreter', 'latex',...
        'FontSize', 12,...
        'FontName', 'Times',...
        'Location', 'Best')
end
%% Title
if ~isempty(Axes.Title.String)
    title(Axes.Title.String,...
        'FontUnits','points',...
        'interpreter', 'latex',...
        'FontWeight','normal',...
        'FontSize',12,...
        'FontName','Times')
end
%% Right Y-Axis
% yyaxis right
% Axes = gca;
% if ~isempty(Axes.YLabel.String)
%     ylabel(Axes.YLabel.String,...
%         'FontUnits', 'points',...
%         'interpreter', 'latex',...
%         'FontSize', 12,...
%         'FontName','Times')
% end
end